name: dk2

on: 
    workflow_dispatch:
    schedule:
    - cron: '30 0,4,8,12,16,20,23 * * *'

env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          releases_keep_latest: 360
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 360

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          check-latest: true
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '运行【多看阅读】' 
        run: python3 main.py 
        env:
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            COOKIES: ${{ secrets.COOKIES }}
